spring:
  application:
    name: weather-aggregator
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: weather
    password: 'qwerty$4'
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/weather
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    pool:
      initial-size: 1
      min-idle: 1
      max-size: 5
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans